/**
 * test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnObjectWithDouble.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AnObjectWithDouble_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AnObjectWithDouble_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  AnObjectWithDouble
    : public ModelBase
{
public:
    AnObjectWithDouble();
    virtual ~AnObjectWithDouble();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AnObjectWithDouble members

    /// <summary>
    /// 
    /// </summary>
    double getNum1() const;
    bool num1IsSet() const;
    void unsetNum1();

    void setNum1(double value);

    /// <summary>
    /// 
    /// </summary>
    double getNum2() const;
    bool num2IsSet() const;
    void unsetNum2();

    void setNum2(double value);


protected:
    double m_Num1;
    bool m_Num1IsSet;
    double m_Num2;
    bool m_Num2IsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AnObjectWithDouble_H_ */
